{{- if .Values.operator.leaderElection -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "buildkit-operator.leaderElectionRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: buildkit-operator
    app.kubernetes.io/part-of: buildkit-operator
    {{- include "buildkit-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "buildkit-operator.leaderElectionRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "buildkit-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
