apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "buildkit-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: buildkit-operator
    app.kubernetes.io/part-of: buildkit-operator
    control-plane: controller-manager
    {{- include "buildkit-operator.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "buildkit-operator.selectorLabels" . | nindent 6 }}
