{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "buildkit-operator.fullname" . }}-mutating-webhook-configuration
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: buildkit-operator
    app.kubernetes.io/part-of: buildkit-operator
    {{- include "buildkit-operator.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "buildkit-operator.fullname" . }}-serving-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "buildkit-operator.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-buildkit-seatgeek-io-v1alpha1-buildkittemplate
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
  name: mbuildkittemplate.kb.io
  rules:
  - apiGroups:
    - buildkit.seatgeek.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - buildkittemplates
  sideEffects: None
{{- end }}
