// Code generated by client-gen-v0.32. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/seatgeek/buildkit-operator/api/client/versioned/typed/api/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeBuildkitV1alpha1 struct {
	*testing.Fake
}

func (c *FakeBuildkitV1alpha1) Buildkits(namespace string) v1alpha1.BuildkitInterface {
	return newFakeBuildkits(c, namespace)
}

func (c *FakeBuildkitV1alpha1) BuildkitTemplates(namespace string) v1alpha1.BuildkitTemplateInterface {
	return newFakeBuildkitTemplates(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeBuildkitV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
