// Code generated by client-gen-v0.32. DO NOT EDIT.

package internalversion

import (
	http "net/http"

	scheme "github.com/seatgeek/buildkit-operator/api/client/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type V1alpha1Interface interface {
	RESTClient() rest.Interface
	BuildkitsGetter
	BuildkitTemplatesGetter
}

// V1alpha1Client is used to interact with features provided by the v1alpha1 group.
type V1alpha1Client struct {
	restClient rest.Interface
}

func (c *V1alpha1Client) Buildkits(namespace string) BuildkitInterface {
	return newBuildkits(c, namespace)
}

func (c *V1alpha1Client) BuildkitTemplates(namespace string) BuildkitTemplateInterface {
	return newBuildkitTemplates(c, namespace)
}

// NewForConfig creates a new V1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*V1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new V1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*V1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &V1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new V1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *V1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new V1alpha1Client for the given RESTClient.
func New(c rest.Interface) *V1alpha1Client {
	return &V1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	config.APIPath = "/apis"
	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
	if config.GroupVersion == nil || config.GroupVersion.Group != scheme.Scheme.PrioritizedVersionsForGroup("v1alpha1")[0].Group {
		gv := scheme.Scheme.PrioritizedVersionsForGroup("v1alpha1")[0]
		config.GroupVersion = &gv
	}
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs)

	if config.QPS == 0 {
		config.QPS = 5
	}
	if config.Burst == 0 {
		config.Burst = 10
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *V1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
