// Code generated by client-gen-v0.32. DO NOT EDIT.

package fake

import (
	internalversion "github.com/seatgeek/buildkit-operator/api/client/versioned/typed/v1alpha1/internalversion"
	v1alpha1 "github.com/seatgeek/buildkit-operator/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBuildkitTemplates implements BuildkitTemplateInterface
type fakeBuildkitTemplates struct {
	*gentype.FakeClientWithList[*v1alpha1.BuildkitTemplate, *v1alpha1.BuildkitTemplateList]
	Fake *FakeBuildkit
}

func newFakeBuildkitTemplates(fake *FakeBuildkit, namespace string) internalversion.BuildkitTemplateInterface {
	return &fakeBuildkitTemplates{
		gentype.NewFakeClientWithList[*v1alpha1.BuildkitTemplate, *v1alpha1.BuildkitTemplateList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("buildkittemplates"),
			v1alpha1.SchemeGroupVersion.WithKind("BuildkitTemplate"),
			func() *v1alpha1.BuildkitTemplate { return &v1alpha1.BuildkitTemplate{} },
			func() *v1alpha1.BuildkitTemplateList { return &v1alpha1.BuildkitTemplateList{} },
			func(dst, src *v1alpha1.BuildkitTemplateList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.BuildkitTemplateList) []*v1alpha1.BuildkitTemplate {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.BuildkitTemplateList, items []*v1alpha1.BuildkitTemplate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
