// Code generated by client-gen-v0.32. DO NOT EDIT.

package fake

import (
	internalversion "github.com/seatgeek/buildkit-operator/api/client/versioned/typed/v1alpha1/internalversion"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeV1alpha1 struct {
	*testing.Fake
}

func (c *FakeV1alpha1) Buildkits(namespace string) internalversion.BuildkitInterface {
	return newFakeBuildkits(c, namespace)
}

func (c *FakeV1alpha1) BuildkitTemplates(namespace string) internalversion.BuildkitTemplateInterface {
	return newFakeBuildkitTemplates(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
