// Code generated by client-gen-v0.32. DO NOT EDIT.

package fake

import (
	internalversion "github.com/seatgeek/buildkit-operator/api/client/versioned/typed/v1alpha1/internalversion"
	v1alpha1 "github.com/seatgeek/buildkit-operator/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBuildkits implements BuildkitInterface
type fakeBuildkits struct {
	*gentype.FakeClientWithList[*v1alpha1.Buildkit, *v1alpha1.BuildkitList]
	Fake *FakeBuildkit
}

func newFakeBuildkits(fake *FakeBuildkit, namespace string) internalversion.BuildkitInterface {
	return &fakeBuildkits{
		gentype.NewFakeClientWithList[*v1alpha1.Buildkit, *v1alpha1.BuildkitList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("buildkits"),
			v1alpha1.SchemeGroupVersion.WithKind("Buildkit"),
			func() *v1alpha1.Buildkit { return &v1alpha1.Buildkit{} },
			func() *v1alpha1.BuildkitList { return &v1alpha1.BuildkitList{} },
			func(dst, src *v1alpha1.BuildkitList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.BuildkitList) []*v1alpha1.Buildkit { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.BuildkitList, items []*v1alpha1.Buildkit) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
