{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "buildkit-operator.managerRoleName" . }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: buildkit-operator
    app.kubernetes.io/part-of: buildkit-operator
    {{- include "buildkit-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "buildkit-operator.managerRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "buildkit-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
